#if DEBUG
using Dalamud.Bindings.ImGui;
using FFXIVClientStructs.FFXIV.Component.GUI;
using GlamourLog.Nodes.GuideWindow;
using System.Globalization;
using System.Text;

namespace GlamourLog.Windows.GuideWindow;

internal sealed class PcSearchSelectClassDebugGuidePage : IGuidePage {
    public string Id => "debug.pc-search-select-class";
    public GuideCategory Category => GuideCategory.Debug;
    public int Order => 1;
    public string Title => "PcSearchSelectClass";

    public IReadOnlyList<IGuideBlock> BuildBlocks(GuidePageContext context)

        => [
            new DebugActionButtonBlock("Dump PcSearchSelectClass", DumpPcSearchSelectClass),
            new JobPickerDebugBlock(),
        ];

    private unsafe void DumpPcSearchSelectClass() {
        var addon = IGameGui.Get().GetAddonByName<AtkUnitBase>(Title);
        if (addon is null || !addon->IsReady || addon->AtkValues is null || addon->AtkValuesCount == 0) {
            IPluginLog.Get().Warning($"[{nameof(GuideWindow)}] Cannot dump {Title}");
            return;
        }

        try {
            var addonId = addon->Id;
            var valueCount = addon->AtkValuesCount;
            var snapshots = new CapturedAtkValue[valueCount];
            var stringCount = 0;

            for (var i = 0; i < valueCount; i++)
                snapshots[i] = CaptureAtkValue(addon->AtkValues[i], ref stringCount);

            var source = GeneratePcSearchSelectClassSetupData(snapshots);
            ImGui.SetClipboardText(source);
            IPluginLog.Get().Info(
                $"[{nameof(GuideWindow)}] Dumped {Title}: " +
                $"addon ID={addonId}, AtkValue count={valueCount}, strings={stringCount}, output length={source.Length}.");
        }
        catch (Exception ex) {
            IPluginLog.Get().Error(ex, $"[{nameof(GuideWindow)}] Failed to dump {Title}.");
        }
    }

    private static unsafe CapturedAtkValue CaptureAtkValue(AtkValue value, ref int stringCount) {
        switch (value.Type) {
            case AtkValueType.Undefined:
            case AtkValueType.Null:
                return new(value.Type, "null", null);
            case AtkValueType.Bool:
                return new(value.Type, value.Bool ? "true" : "false", null);
            case AtkValueType.Int:
                return new(value.Type, value.Int.ToString(CultureInfo.InvariantCulture), null);
            case AtkValueType.Int64:
                return new(value.Type, FormatInt64(value.Int64), null);
            case AtkValueType.UInt:
                return new(value.Type, value.UInt.ToString(CultureInfo.InvariantCulture) + "U", null);
            case AtkValueType.UInt64:
                return new(value.Type, value.UInt64.ToString(CultureInfo.InvariantCulture) + "UL", null);
            case AtkValueType.Float:
                return new(value.Type, FormatFloat(value.Float), null);
            case AtkValueType.String:
            case AtkValueType.ManagedString:
            case AtkValueType.ConstString:
                stringCount++;
                var utf8Text = value.String.HasValue ? value.String.ToString() : string.Empty;
                return new(value.Type, ToCSharpStringLiteral(utf8Text), null);
            case AtkValueType.WideString:
                stringCount++;
                var text = value.WideString is null ? string.Empty : new string(value.WideString);
                return new(value.Type, ToCSharpStringLiteral(text), null);
            case AtkValueType.Vector:
            case AtkValueType.ManagedVector:
            case AtkValueType.Pointer:
            case AtkValueType.AtkValues:
                return new(value.Type, "null", "Pointer-valued data omitted intentionally.");
            default:
                return new(value.Type, "null", "Unsupported AtkValue type omitted intentionally.");
        }
    }

    private string GeneratePcSearchSelectClassSetupData(IReadOnlyList<CapturedAtkValue> values) {
        var source = new StringBuilder(256 + values.Count * 64);
        source.AppendLine("// <auto-generated>");
        source.AppendLine($"// Captured from {Title}.");
        source.AppendLine("// Do not edit manually; regenerate from GlamourLog's debug page.");
        source.AppendLine("// </auto-generated>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("using FFXIVClientStructs.FFXIV.Component.GUI;");
        source.AppendLine();
        source.AppendLine("namespace GlamourLog.Windows.JobPicker;");
        source.AppendLine();
        source.AppendLine("internal static class PcSearchSelectClassSetupData {");
        source.Append("    internal const int CapturedValueCount = ")
            .Append(values.Count.ToString(CultureInfo.InvariantCulture))
            .AppendLine(";");
        source.AppendLine();
        source.AppendLine("    internal static readonly AtkValueSnapshot[] Values =");
        source.AppendLine("    [");

        foreach (var value in values) {
            source.Append("        new(")
                .Append(FormatAtkValueType(value.Type))
                .Append(", ")
                .Append(value.ValueExpression)
                .Append("),");
            if (value.Comment is not null)
                source.Append(" // ").Append(value.Comment);
            source.AppendLine();
        }

        source.AppendLine("    ];");
        source.AppendLine();
        source.AppendLine("    internal readonly record struct AtkValueSnapshot(AtkValueType Type, object? Value);");
        source.AppendLine("}");
        return source.ToString();
    }

    private static string FormatAtkValueType(AtkValueType type)
        => type switch {
            AtkValueType.Undefined => "AtkValueType.Undefined",
            AtkValueType.Null => "AtkValueType.Null",
            AtkValueType.Bool => "AtkValueType.Bool",
            AtkValueType.Int => "AtkValueType.Int",
            AtkValueType.Int64 => "AtkValueType.Int64",
            AtkValueType.UInt => "AtkValueType.UInt",
            AtkValueType.UInt64 => "AtkValueType.UInt64",
            AtkValueType.Float => "AtkValueType.Float",
            AtkValueType.String => "AtkValueType.String",
            AtkValueType.WideString => "AtkValueType.WideString",
            AtkValueType.ConstString => "AtkValueType.ConstString",
            AtkValueType.Vector => "AtkValueType.Vector",
            AtkValueType.Pointer => "AtkValueType.Pointer",
            AtkValueType.AtkValues => "AtkValueType.AtkValues",
            AtkValueType.ManagedString => "AtkValueType.ManagedString",
            AtkValueType.ManagedVector => "AtkValueType.ManagedVector",
            _ => $"(AtkValueType){((int)type).ToString(CultureInfo.InvariantCulture)}",
        };

    private static string FormatInt64(long value)
        => value == long.MinValue ? "long.MinValue" : value.ToString(CultureInfo.InvariantCulture) + "L";

    private static string FormatFloat(float value) {
        if (float.IsNaN(value))
            return "float.NaN";
        if (float.IsPositiveInfinity(value))
            return "float.PositiveInfinity";
        if (float.IsNegativeInfinity(value))
            return "float.NegativeInfinity";
        return value.ToString("R", CultureInfo.InvariantCulture) + "F";
    }

    private static string ToCSharpStringLiteral(string value) {
        var escaped = new StringBuilder(value.Length + 2);
        escaped.Append('"');
        foreach (var character in value) {
            switch (character) {
                case '"':
                    escaped.Append("\\\"");
                    break;
                case '\\':
                    escaped.Append("\\\\");
                    break;
                case '\n':
                    escaped.Append("\\n");
                    break;
                case '\r':
                    escaped.Append("\\r");
                    break;
                case '\t':
                    escaped.Append("\\t");
                    break;
                default:
                    if (char.IsControl(character) || char.IsSurrogate(character) ||
                        character is '\u2028' or '\u2029') {
                        escaped.Append("\\u")
                            .Append(((int)character).ToString("X4", CultureInfo.InvariantCulture));
                    }
                    else {
                        escaped.Append(character);
                    }
                    break;
            }
        }
        return escaped.Append('"').ToString();
    }

    private readonly record struct CapturedAtkValue(AtkValueType Type, string ValueExpression, string? Comment);

    private sealed record DebugActionButtonBlock(string Label, System.Action OnClick) : GuideBlock<DebugActionButtonNode> {
        protected override DebugActionButtonNode Create(float width) => new(width, Label, OnClick);
        protected override void Relayout(DebugActionButtonNode node, float width) => node.Relayout(width);
    }

    private sealed record JobPickerDebugBlock : GuideBlock<JobPickerDebugRowNode> {
        protected override JobPickerDebugRowNode Create(float width) => new(width);
        protected override void Relayout(JobPickerDebugRowNode node, float width) => node.Relayout(width);
    }
}
#endif
